name: Own project pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  own_project_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: # These are for tagging releases
          ref: ${{ github.sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          file_name: .env
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build:ui
      - name: test
        run: npm run test
      - name: Deploy to Heroku
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip')
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "own-app-pipeline"
          heroku_email: "valtteri.ingervo@aalto.fi"
          healthcheck: "https://own-app-pipeline.herokuapp.com/health"
          checkstring: "ok"
          delay: 3
          rollbackonhealthcheckfailed: true
      - name: Tag release
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip')
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
