name: Own project pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  own_project_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          file_name: .env
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build:ui
      - name: test
        run: npm run test
